# Generated by Django 4.2.16 on 2024-12-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OTC", "Over The Counter"),
                            ("PRE", "Prescription"),
                            ("SUP", "Supplements"),
                            ("COS", "Cosmetics"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="medicines/"),
                ),
                ("barcode", models.ImageField(blank=True, upload_to="barcodes/")),
                (
                    "barcode_number",
                    models.CharField(blank=True, max_length=13, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
