# Generated by Django 4.2.16 on 2025-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="can_sell_strips",
            field=models.BooleanField(
                default=False, help_text="هل يمكن بيع أشرطة منفردة؟"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="strips_per_box",
            field=models.PositiveIntegerField(
                default=1, help_text="عدد الأشرطة في العلبة الواحدة"
            ),
        ),
    ]
