# Generated by Django 4.2.16 on 2025-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_medicine_can_sell_strips_medicine_strips_per_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="strip_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per strip (optional - if not set, will be calculated from box price)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="can_sell_strips",
            field=models.BooleanField(
                default=True, help_text="Allow selling individual strips"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="strips_per_box",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of strips per box"
            ),
        ),
    ]
