# Generated by Django 4.2.16 on 2024-12-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_medicine_expiration_date_stockentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="expiration_date",
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
