# Generated by Django 4.2.16 on 2025-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pharmacy",
            "0003_medicine_strip_price_alter_medicine_can_sell_strips_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="unit_type",
            field=models.CharField(
                choices=[("BOX", "Box"), ("STRIP", "Strip")],
                default="BOX",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
