# Generated by Django 4.2.16 on 2024-12-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_remove_medicine_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="barcode_number",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
