# Generated by Django 4.2.16 on 2025-04-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0004_saleitem_unit_type_alter_saleitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Cost price of the product",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
