# Generated by Django 4.2.16 on 2025-04-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0005_medicine_purchase_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("number_of_sales", models.IntegerField(default=0)),
                (
                    "average_profit_per_sale",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "most_profitable_category",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "most_profitable_medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_profit_days",
                        to="pharmacy.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profit analytics",
                "ordering": ["-date"],
            },
        ),
    ]
