# Generated by Django 4.2.16 on 2025-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0006_profitanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "عميل عادي"),
                    ("FAMILY", "من الأقارب"),
                    ("VIP", "عميل مميز"),
                    ("WHOLESALE", "تاجر جملة"),
                ],
                default="REGULAR",
                max_length=20,
                verbose_name="نوع العميل",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="نسبة الخصم الخاصة بالعميل",
                max_digits=5,
            ),
        ),
    ]
