# Generated by Django 4.2.16 on 2024-12-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0007_purchase_supplier_purchaseitem_purchase_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="reorder_level",
            field=models.IntegerField(
                default=10, help_text="Minimum stock level before reorder"
            ),
        ),
    ]
