# Generated by Django 4.2.16 on 2024-12-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0010_userprofile_bio_userprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=100)),
                ("doctor_contact", models.CharField(blank=True, max_length=20)),
                ("prescription_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISPENSED", "Dispensed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFILL_REQUESTED", "Refill Requested"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.customer",
                    ),
                ),
            ],
        ),
    ]
